import { ReactNode } from 'react'
import type { Metadata } from 'next'
import Header from '@/widgets/Header/header'
import Footer from '@/widgets/Footer/footer'
import './globals.css'


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang='en'>
        <body>
            <Header/>
            <main>
                {children}
            </main>
            <Footer/>
        </body>
        </html>
    )
}
